catetoOposto = float(input("Insira o valor do cateto oposto: "))
catetoAdjacente = float(input("Insira o valor do cateto adjacente: "))
hipotenusa  = ((catetoOposto ** 2) + (catetoAdjacente ** 2)) ** (1/2)
# print("Hipotenusa = ", round(hipotenusa, 2))
print("Hipotenusa = {:.2f}".format(hipotenusa))